### ISSUE TITLE
#US06 - Como integrante del equipo de trabajo Quiero revisar el diagrama de caso de uso Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#10]
**Descripción.
Como integrante del equipo de trabajo
Quiero revisar el diagrama de caso de uso
Para continuar con el avance del proyecto integrador.

**Criterios de aceptación.

Escenario 1: En caso de necesitar avanzar con el proyecto, necesitamos que se controle el diagrama de caso de uso para poder tener una base para continuar trabajando.

**Comment by AgustinRios263** [comment]
![image](https://user-images.githubusercontent.com/106454275/233238178-0d3727dc-2cc1-42f9-9508-053e3398ad1c.png)
