### ISSUE TITLE
#US10 - Como integrante del equipo de trabajo Quiero crear un script legible de la BD en MySQL Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#19]
## Descripción.
Como integrante del equipo de trabajo 
Quiero crear un script legible de la BD en MySQL 
Para continuar con el avance del proyecto integrador.

## Criterios de aceptación.

Escenario 1: 
En caso de que los profesores necesiten ver el script generador de la base de datos, necesitamos que sea legible y bien realizado para que los profesores entiendan su correcto funcionamiento.

**Comment by memaluna** [comment]
![Image](https://user-images.githubusercontent.com/34133110/234147559-5287d33f-a530-4493-808c-07c5bab13a86.JPG)

Dejo esto para tenerrlo cerquita!

**Comment by GiulianaDeEt** [comment]
![image](https://user-images.githubusercontent.com/96992783/236600861-abd6b080-2959-481f-b027-66c6a5774adc.png)
