### ISSUE TITLE
#US12 - Como integrante del equipo de trabajo Quiero diseñar la Normalización usando como referencia los diagramas realizados Para administrar continuar con el avance del proyecto.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#21]
## Descripción. 
Como
Quiero
Para 

## Criterios de aceptación.

**Escenario 1:** En caso de (...), necesitamos que (...) para (...).

**Comment by GiulianaDeEt** [comment]
Dejo los links para comprender mejor que el la normalización:
• https://www.youtube.com/watch?v=yk1zsifJbWg
• https://www.youtube.com/watch?v=lfPq6Fi_3iQ
• https://www.youtube.com/watch?v=R2MX-Yd0LXU
• https://bookdown.org/paranedagarcia/database/normalizacion.html
• https://www.aluracursos.com/blog/normalizacion-en-base-de-datos

**Comment by AgustinRios263** [comment]
![Normalizacion de Productos](https://user-images.githubusercontent.com/106454275/235547002-02b5ed27-f5e9-4e04-8d85-d279a39177da.jpeg)
Se realiza normalizacion de productos

**Comment by vittoria06** [comment]
(https://user-images.githubusercontent.com/108439032/235549513-31e5e378-181c-43fc-9f07-c4b030396451.jpg)



se hizo una corrección en la normalización de los datos de usuarios

**Comment by vittoria06** [comment]
[imagen.pdf](https://github.com/TEAM-ISPC/E-commerce/files/11368803/imagen.pdf)


se corrigió la normalización de los datos de usuarios

**Comment by vittoria06** [comment]
(https://user-images.githubusercontent.com/108439032/235555076-5c007615-e1b3-450c-ae60-0e66ad380343.jpg)

se corrigió la normalización de los datos de usuarios

**Comment by vittoria06** [comment]
images.githubusercontent.com/108439032/235555290-8db84f7a-d38a-47eb-b524-e0549b262811.jpg)


se corrigió la normalización de los datos de usuarios

**Comment by vittoria06** [comment]
![imagen de diagrama](https://user-images.githubusercontent.com/108439032/235555931-504af85d-2288-4a03-8e9f-d2cd50b4c407.jpg)

se corrigió la normalización de los datos de usuarios
