### ISSUE TITLE
#US13 - Como integrante del equipo de trabajo Quiero convertir los archivos .html en una SPA en Angular con módulos y componentes Para continuar con el avance del proyecto

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#22]
##Descripción.
Como inegrante del equipo de trabajo Quiero convertir los archivos .html en una SPA en Angular con módulos y componentes Para continuar con el avance del proyecto.

##Criterios de aceptación.
Escenario 1: En caso de necesitar avanzar con el proyecto, es necesario convertir en SPA la tienda con Angular para poder continuar con el desarrollo del proyecto.

##Lista de tareas
- [x] #TK04 - Login
- [ ] #TK05 - Registro
- [x] #TK06 - Home
- [x] #TK07 - Productos
- [x] #TK08 - Details del producto
- [x] #TK09 - Carrito
- [ ] #TK10 - Comprobante

**Comment by LucasJuarez3416** [comment]
![Image](https://user-images.githubusercontent.com/33500391/236693994-1c627ced-df1b-43e5-8ffb-dcc00a75dbfe.png)


![Image](https://user-images.githubusercontent.com/33500391/236694016-7d1c4845-0fa5-4095-9715-de88ea8715d7.png)

Se adjuntan imágenes del routing y de los components que se desarrollaron con angular
