### ISSUE TITLE
#US15 - Como integrante del equipo de trabajo Quiero aplicar servicios a los componentes Para continuar con el avance del proyecto integrador. 

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#33]
### Descripción.
Como 
Quiero 
Para 

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

## Lista de tareas

- [x] #TK04 - Incluir enlace de datos (Data binding)

**Comment by solefanjbj** [comment]
![Captura de pantalla servicio http](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/eee38ba0-3cda-4eb3-b9d1-fd646067e664)
