### ISSUE TITLE
#US16 - Como integrante del equipo de trabajo Quiero crear MVC en Django Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#34]
### Descripción.
Como integrante del equipo de trabajo
Quiero crear MVC en Django
Para continuar con el avance del proyecto integrador.

### Criterios de aceptación.

Escenario 1: En caso de necesitar avanzar con el proyecto, es necesario crear un primer MVC para poder tener una base para continuar trabajando.

**Comment by GiulianaDeEt** [comment]
![image](https://github.com/TEAM-ISPC/E-commerce/assets/96992783/d5472593-6412-4910-a000-b67dfcfdcfef)

**Comment by solefanjbj** [comment]
![image](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/a0c2561e-9bfb-4aac-90e5-f860f2b34bd2)
