### ISSUE TITLE
#US17 - Como integrante del equipo de trabajo Quiero crear una simulación de consumir servicios mediante JSON Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#35]
### Descripción.
Como 
Quiero 
Para 

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

**Comment by solefanjbj** [comment]
![Captura de pantalla json](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/f255f50b-924c-44e6-a8fe-7b54022b36eb)
