### ISSUE TITLE
#US18 - Como integrante del equipo de trabajo Quiero implementar formularios reactivos Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#36]
### Descripción.
Como 
Quiero 
 

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

**Comment by solefanjbj** [comment]
![Captura de pantalla formulario reactivo](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/348c1ab7-cd6f-4345-90d6-5fbcbfee133b)
