### ISSUE TITLE
#US19 - Como integrante del equipo de trabajo Quiero servicios en Angular que hagan peticiones HTTP Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#37]
### Descripción.
Como 
Quiero 
 

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

## Lista de tareas

- [ ] #TK05 - Crear servicios que consuman un API Rest de prueba

**Comment by solefanjbj** [comment]
![Captura de pantalla servicio http-1](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/3ef009b9-dc77-4437-adcf-65b3c0957eb9)
