### ISSUE TITLE
#TK04 - Incluir enlace de datos (Data binding)

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#38]
(breve descripción)

Corresponde a #33

**Comment by solefanjbj** [comment]
![Captura de pantalla propertibinding](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/540cb05c-86cf-45de-99f6-3da8e4190943)
![Captura de pantalla databinding](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/d5f6cf75-133a-42ed-9e05-a971fd6307e3)
