### ISSUE TITLE
#TK05 - Crear servicios que consuman un API Rest de prueba

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#41]
Ejemplo de APIR Rest: https://www.npmjs.com/package/json-server

Corresponde a #37

**Comment by solefanjbj** [comment]
![Captura de pantalla servicio http](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/7ed9f57d-79b9-4a3a-be4a-cc28cd7401c1)
