### ISSUE TITLE
#US22 - Como integrante del equipo de trabajo Quiero incorporar programación reactiva mediante observables Para la comunicación entre servicios y componentes

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#42]
### Descripción.
Como
Quiero
Para

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

**Comment by solefanjbj** [comment]
![Captura de pantalla servicio http](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/fb41e013-4f24-4c41-999e-6261b405c72c)
