### ISSUE TITLE
#US25 - Como integrante del equipo de trabajo Quiero diseñar formularios Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#49]
### Descripción.
Como 
Quiero 
Para

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

### Tareas
- [ ] - Deberán estar conformados por INPUT TYPES
- [ ] - Deberán informar al usuario mediante mensajes personalizados (validaciones)
- [ ] - Deberán respetar los colores semánticos de bootstrap

**Comment by solefanjbj** [comment]
![Captura-pantalla-formReactivo-login](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/4d92c909-1208-4ef3-8eab-de766d2542f8)
![Captura-pantalla-formReactivo-registro](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/1a5ac7cd-63c8-42fb-9fb7-137ed9788937)
