### ISSUE TITLE
#US26 - Como integrante del equipo de trabajo Quiero conectar front end con bak end Para el login. 

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#50]
### Descripción.
Como 
Quiero 
Para 

### Criterios de aceptación.

Escenario 1: En caso (...) , es necesario (...) para (...)

**Comment by solefanjbj** [comment]
![Captura-de-pantalla-login-service](https://github.com/TEAM-ISPC/E-commerce/assets/99839173/2da76bbc-3621-4a57-bcd8-c9ad2fb8b777)
