### ISSUE TITLE
#US03 - Como integrante del equipo de trabajo Quiero agregar la parte e-commerce al documento IEEE830 Para completar la documentación del proyecto

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#7]
**Descripción.
Como integrante del equipo de trabajo
Quiero agregar la parte e-commerce al documento IEEE830
Para completar la documentación del proyecto

**Criterios de aceptación.

Escenario 1: En caso que los integrantes necesiten recurrir de la documentación y adicionalmente, verificar si el proyecto va encaminado acorde a lo planeado, el sistema deberá incluir la parte de e-commerce en el documento IEEE830 de manera clara y completa.

**Comment by LucasJuarez3416** [comment]
Finalizamos la actualización del archivo IEEE830 con los requerimientos para E-Commerce
