### ISSUE TITLE
#US04 - Revisar la estructura web Semántica ,responsive (RWD).

### ISSUE THREAD

**Issue by memaluna** [TEAM-ISPC/E-commerce#8]
**Descripción.
Como integrante del equipo de trabajo
Quiero revisar la estructura web Semántica ,responsive (RWD)
Para continuar con el avance del proyecto integrador.

**Criterios de aceptación.

Escenario 1: En caso de necesitar avanzar con el proyecto, necesitamos que se controle la estructura para poder tener una base para continuar trabajando.

**Comment by LucasJuarez3416** [comment]
Se agrega al proyecto un apartado de tienda online donde se accede a la misma a través de un ícono animado en forma de shopbag disponible para el usuario una vez iniciada sesión



![Image](https://user-images.githubusercontent.com/33500391/233381821-3514e666-2df7-4f91-8864-507dbb7ff5e1.png)

Para insertar ese ícono se importó la librería de íconos de FontAwasome y con una etiqueta <a> se lo referencia directamente a la tienda.


La tienda:
![Image](https://user-images.githubusercontent.com/33500391/233382293-bcbce86e-0d17-4a29-a09d-f9f9fa3d508a.png)

Para realizar la tienda se usaron las clases ya definidas en el proyecto con anterioridad en el css y algunas propias de bootstrap. Consta de un header, un nav para el menú donde se idea colocar un filtro y el carrito.
En formato de cards de bootstrap se disponen en grid los artículos en venta donde al hacer click en alguno de estos se abre una nueva ventana con el detalle del mismo

Detalle de producto:


![Image](https://user-images.githubusercontent.com/33500391/233383107-75c096fd-3442-4b61-b689-7cf28cd67276.png)

En el detalle se puede ver una imagen del producto a la izquierda y un detalle escrito en <p> con un lórem de ejemplo y un botón con la clase agregada a las de boostrap "boton" definida en un css personalizado con el hover correspondiente respetando la estética definida para la marca TurNow. 

En un futuro la idea es colocar botones de social en el footer e información de contacto al lado del copyright.
