### ISSUE TITLE
#US05 - Como integrante del equipo de trabajo Quiero revisar el diagrama de clases Para continuar con el avance del proyecto integrador.

### ISSUE THREAD

**Issue by GiulianaDeEt** [TEAM-ISPC/E-commerce#9]
**Descripción.
Como integrante del equipo de trabajo
Quiero revisar el diagrama de clases
Para continuar con el avance del proyecto integrador.

**Criterios de aceptación.

Escenario 1: En caso de necesitar avanzar con el proyecto, necesitamos que se controle el diagrama de clases para poder tener una base para continuar trabajando.

**Comment by solefanjbj** [comment]
![Diagrama UML](https://user-images.githubusercontent.com/99839173/233530778-7e51c6c9-27f4-42bc-b8c4-2083f396707e.jpg)

**Comment by solefanjbj** [comment]
![DiagramaClases-ISPC](https://user-images.githubusercontent.com/99839173/233531601-35b2b885-85c9-4d9d-99bf-d20021bf3410.png)
